from EepromTypes import StructNode, ValueNode, NodeArray, ValueArray
PpCvm441=StructNode("PpCvm441",offset=0x0000, length=4096,
    EepromInRam=StructNode("EepromInRam",offset=0x0000, end=0x0073,
        Ipei=ValueArray("Ipei",offset=0x0000, end=0x0004, dtype="uchar"),
        BmcModulationDeviation=ValueNode("BmcModulationDeviation",offset=0x0005, end=0x0005, dtype="uchar"),
        BmcDefaultFrequency=ValueNode("BmcDefaultFrequency",offset=0x0006, end=0x0007, dtype="ushort"),
        RfLMX4x68Length=ValueNode("RfLMX4x68Length",offset=0x0008, end=0x0008, dtype="uchar"),
        FixedEmc=ValueNode("FixedEmc",offset=0x0009, end=0x000A, dtype="ushort"),
        FixedPhoenixInRamSectionReserved=ValueArray("FixedPhoenixInRamSectionReserved",offset=0x000B, end=0x001F, dtype="uchar"),
        bFreqBandOffset=ValueNode("bFreqBandOffset",offset=0x0020, end=0x0020, dtype="uchar"),
        bRssiScanType=ValueNode("bRssiScanType",offset=0x0021, end=0x0021, dtype="uchar"),
        DiversityMode=ValueNode("DiversityMode",offset=0x0022, end=0x0022, dtype="uchar"),
        bRssiLevel_UpperThreshold=ValueNode("bRssiLevel_UpperThreshold",offset=0x0023, end=0x0023, dtype="uchar"),
        bRssiLevel_LowerThreshold=ValueNode("bRssiLevel_LowerThreshold",offset=0x0024, end=0x0024, dtype="uchar"),
        ParkA=ValueArray("ParkA",offset=0x0025, end=0x0029, dtype="uchar"),
        ParkB=ValueArray("ParkB",offset=0x002A, end=0x002E, dtype="uchar"),
        ParkC=ValueArray("ParkC",offset=0x002F, end=0x0033, dtype="uchar"),
        ParkD=ValueArray("ParkD",offset=0x0034, end=0x0038, dtype="uchar"),
        PliA=ValueNode("PliA",offset=0x0039, end=0x0039, dtype="uchar"),
        PliB=ValueNode("PliB",offset=0x003A, end=0x003A, dtype="uchar"),
        PliC=ValueNode("PliC",offset=0x003B, end=0x003B, dtype="uchar"),
        PliD=ValueNode("PliD",offset=0x003C, end=0x003C, dtype="uchar"),
        PowerParameters=ValueNode("PowerParameters",offset=0x003D, end=0x003D, dtype="uchar"),
        CoverageBeepLimit=ValueNode("CoverageBeepLimit",offset=0x003E, end=0x003E, dtype="uchar"),
        AdaptivePowerCtrl=ValueNode("AdaptivePowerCtrl",offset=0x003F, end=0x003F, dtype="uchar"),
        PowerLowRssiLimit=ValueNode("PowerLowRssiLimit",offset=0x0040, end=0x0040, dtype="uchar"),
        PowerHighRssiLimit=ValueNode("PowerHighRssiLimit",offset=0x0041, end=0x0041, dtype="uchar"),
        PowerCrcLimit=ValueNode("PowerCrcLimit",offset=0x0042, end=0x0042, dtype="uchar"),
        PowerCrcHighCnt=ValueNode("PowerCrcHighCnt",offset=0x0043, end=0x0043, dtype="uchar"),
        HandoverFreqDist=ValueNode("HandoverFreqDist",offset=0x0044, end=0x0044, dtype="uchar"),
        ClSelect=ValueNode("ClSelect",offset=0x0045, end=0x0045, dtype="uchar"),
        ScFlags=ValueNode("ScFlags",offset=0x0046, end=0x0046, dtype="uchar"),
        ProtocolFeatures=ValueNode("ProtocolFeatures",offset=0x0047, end=0x0047, dtype="uchar"),
        ProtocolFeatures2=ValueNode("ProtocolFeatures2",offset=0x0048, end=0x0048, dtype="uchar"),
        RfPower4x1=NodeArray("RfPower4x1",offset=0x0049, end=0x006C, nodes=[
            StructNode("Element 0",offset=0x0049, end=0x004E,
                PA_CTRL1_REG=ValueArray("PA_CTRL1_REG",offset=0x0049, end=0x004A, dtype="uchar"),
                TEST_MODE2_REG=ValueArray("TEST_MODE2_REG",offset=0x004B, end=0x004C, dtype="uchar"),
                BBADC_CTRL_REG=ValueArray("BBADC_CTRL_REG",offset=0x004D, end=0x004E, dtype="uchar")
            ),
            StructNode("Element 1",offset=0x004F, end=0x0054,
                PA_CTRL1_REG=ValueArray("PA_CTRL1_REG",offset=0x004F, end=0x0050, dtype="uchar"),
                TEST_MODE2_REG=ValueArray("TEST_MODE2_REG",offset=0x0051, end=0x0052, dtype="uchar"),
                BBADC_CTRL_REG=ValueArray("BBADC_CTRL_REG",offset=0x0053, end=0x0054, dtype="uchar")
            ),
            StructNode("Element 2",offset=0x0055, end=0x005A,
                PA_CTRL1_REG=ValueArray("PA_CTRL1_REG",offset=0x0055, end=0x0056, dtype="uchar"),
                TEST_MODE2_REG=ValueArray("TEST_MODE2_REG",offset=0x0057, end=0x0058, dtype="uchar"),
                BBADC_CTRL_REG=ValueArray("BBADC_CTRL_REG",offset=0x0059, end=0x005A, dtype="uchar")
            ),
            StructNode("Element 3",offset=0x005B, end=0x0060,
                PA_CTRL1_REG=ValueArray("PA_CTRL1_REG",offset=0x005B, end=0x005C, dtype="uchar"),
                TEST_MODE2_REG=ValueArray("TEST_MODE2_REG",offset=0x005D, end=0x005E, dtype="uchar"),
                BBADC_CTRL_REG=ValueArray("BBADC_CTRL_REG",offset=0x005F, end=0x0060, dtype="uchar")
            ),
            StructNode("Element 4",offset=0x0061, end=0x0066,
                PA_CTRL1_REG=ValueArray("PA_CTRL1_REG",offset=0x0061, end=0x0062, dtype="uchar"),
                TEST_MODE2_REG=ValueArray("TEST_MODE2_REG",offset=0x0063, end=0x0064, dtype="uchar"),
                BBADC_CTRL_REG=ValueArray("BBADC_CTRL_REG",offset=0x0065, end=0x0066, dtype="uchar")
            ),
            StructNode("Element 5",offset=0x0067, end=0x006C,
                PA_CTRL1_REG=ValueArray("PA_CTRL1_REG",offset=0x0067, end=0x0068, dtype="uchar"),
                TEST_MODE2_REG=ValueArray("TEST_MODE2_REG",offset=0x0069, end=0x006A, dtype="uchar"),
                BBADC_CTRL_REG=ValueArray("BBADC_CTRL_REG",offset=0x006B, end=0x006C, dtype="uchar")
            )
        ]
        ),
        Lu10Config=ValueNode("Lu10Config",offset=0x006D, end=0x006D, dtype="uchar"),
        bEarlyEncryption_DefaultKeyAssigned=ValueNode("bEarlyEncryption_DefaultKeyAssigned",offset=0x006E, end=0x006E, dtype="uchar"),
        ProtocolFeatures3=ValueNode("ProtocolFeatures3",offset=0x006F, end=0x006F, dtype="uchar"),
        Lu10Debug=ValueNode("Lu10Debug",offset=0x0070, end=0x0070, dtype="uchar"),
        ProtocolFeatures4=ValueNode("ProtocolFeatures4",offset=0x0071, end=0x0071, dtype="uchar"),
        ProtocolFeatures5=ValueNode("ProtocolFeatures5",offset=0x0072, end=0x0072, dtype="uchar"),
        PwrCountryMask=ValueNode("PwrCountryMask",offset=0x0073, end=0x0073, dtype="uchar")
    ),
    EepromNotInRam=StructNode("EepromNotInRam",offset=0x0074, end=0x0FFF,
        EepromInRamReserved=ValueArray("EepromInRamReserved",offset=0x0074, end=0x007F, dtype="uchar"),
        InitialTestMode=ValueNode("InitialTestMode",offset=0x0080, end=0x0080, dtype="uchar"),
        Bandgap=ValueNode("Bandgap",offset=0x0081, end=0x0081, dtype="uchar"),
        EeVersion=ValueNode("EeVersion",offset=0x0082, end=0x0082, dtype="uchar"),
        DspPatchCodeStartAddr=ValueNode("DspPatchCodeStartAddr",offset=0x0083, end=0x0084, dtype="ushort"),
        BootMode=ValueNode("BootMode",offset=0x0085, end=0x0085, dtype="uchar"),
        LogError=StructNode("LogError",offset=0x0086, end=0x0095,
            Error=ValueNode("Error",offset=0x0086, end=0x0087, dtype="ushort"),
            Line=ValueNode("Line",offset=0x0088, end=0x0089, dtype="ushort"),
            Info=ValueNode("Info",offset=0x008A, end=0x008D, dtype="ulong"),
            Address=ValueNode("Address",offset=0x008E, end=0x0091, dtype="ulong"),
            Timestamp=ValueNode("Timestamp",offset=0x0092, end=0x0095, dtype="ulong")
        ),
        LogAssert=StructNode("LogAssert",offset=0x0096, end=0x00AA,
            NextAssertId=ValueNode("NextAssertId",offset=0x0096, end=0x0096, dtype="uchar"),
            AssertAddress=ValueArray("AssertAddress",offset=0x0097, end=0x00AA, dtype="ulong")
        ),
        ImageCfg=ValueNode("ImageCfg",offset=0x00AB, end=0x00AB, dtype="uchar"),
        BmcModulationDeviationReduced=ValueNode("BmcModulationDeviationReduced",offset=0x00AC, end=0x00AC, dtype="uchar"),
        PxReserved1=ValueArray("PxReserved1",offset=0x00AD, end=0x00AF, dtype="uchar"),
        RfLMX4x68Data=ValueArray("RfLMX4x68Data",offset=0x00B0, end=0x00D7, dtype="uchar"),
        PxReserved2=ValueArray("PxReserved2",offset=0x00D8, end=0x00DF, dtype="uchar"),
        ProdTest=ValueArray("ProdTest",offset=0x00E0, end=0x00FF, dtype="uchar"),
        FixedPhoenixNotInRamSectionReserved=ValueArray("FixedPhoenixNotInRamSectionReserved",offset=0x0100, end=0x0109, dtype="uchar"),
        AutoTest=ValueNode("AutoTest",offset=0x010A, end=0x010A, dtype="uchar"),
        Unused_Byte1=ValueArray("Unused_Byte1",offset=0x010B, end=0x010C, dtype="uchar"),
        LockToFp=ValueArray("LockToFp",offset=0x010D, end=0x0111, dtype="uchar"),
        EepromUsedRfCarriers=ValueArray("EepromUsedRfCarriers",offset=0x0112, end=0x0113, dtype="uchar"),
        UsedRfCarriers_5g8=ValueArray("UsedRfCarriers_5g8",offset=0x0114, end=0x0119, dtype="uchar"),
        bUSDect8hourHandoverStart=ValueNode("bUSDect8hourHandoverStart",offset=0x011A, end=0x011A, dtype="uchar"),
        bUSDect8hourHandoverRelease=ValueNode("bUSDect8hourHandoverRelease",offset=0x011B, end=0x011B, dtype="uchar"),
        DeleteCauseArr=ValueArray("DeleteCauseArr",offset=0x011C, end=0x012B, dtype="uchar"),
        DeleteRfpi_1=ValueArray("DeleteRfpi_1",offset=0x012C, end=0x0130, dtype="uchar"),
        DeleteRfpi_2=ValueArray("DeleteRfpi_2",offset=0x0131, end=0x0135, dtype="uchar"),
        BmcConfig=StructNode("BmcConfig",offset=0x0136, end=0x013B,
            S_err=ValueNode("S_err",offset=0x0136, end=0x0136, dtype="uchar"),
            Slide_Mask=ValueNode("Slide_Mask",offset=0x0137, end=0x0137, dtype="uchar"),
            Vol=ValueNode("Vol",offset=0x0138, end=0x0138, dtype="uchar"),
            DAC=ValueNode("DAC",offset=0x0139, end=0x0139, dtype="uchar"),
            WIN=ValueNode("WIN",offset=0x013A, end=0x013A, dtype="uchar"),
            Enc=ValueNode("Enc",offset=0x013B, end=0x013B, dtype="uchar")
        ),
        default_BMC_CTRL_REG=ValueNode("default_BMC_CTRL_REG",offset=0x013C, end=0x013C, dtype="uchar"),
        default_BMC_CTRL2_REG=ValueNode("default_BMC_CTRL2_REG",offset=0x013D, end=0x013D, dtype="uchar"),
        HighRssiLimit=ValueNode("HighRssiLimit",offset=0x013E, end=0x013E, dtype="uchar"),
        HighRssiTime=ValueNode("HighRssiTime",offset=0x013F, end=0x013F, dtype="uchar"),
        bNoEmissionModeEnable=ValueNode("bNoEmissionModeEnable",offset=0x0140, end=0x0140, dtype="uchar"),
        bNoEmissionMode_PreferredCarrier=ValueArray("bNoEmissionMode_PreferredCarrier",offset=0x0141, end=0x0144, dtype="uchar"),
        EncStartCheckTime=ValueNode("EncStartCheckTime",offset=0x0145, end=0x0145, dtype="uchar"),
        ExtendedRfCarriers=ValueArray("ExtendedRfCarriers",offset=0x0146, end=0x0148, dtype="uchar"),
        RfDebug=ValueNode("RfDebug",offset=0x0149, end=0x0149, dtype="uchar"),
        RfMacreserved=ValueArray("RfMacreserved",offset=0x014A, end=0x0160, dtype="uchar"),
        HsBatterySettings=StructNode("HsBatterySettings",offset=0x0161, end=0x0196,
            EmptyVoltage=ValueNode("EmptyVoltage",offset=0x0161, end=0x0162, dtype="ushort"),
            LowVoltage=ValueNode("LowVoltage",offset=0x0163, end=0x0164, dtype="ushort"),
            MaxVoltage=ValueNode("MaxVoltage",offset=0x0165, end=0x0166, dtype="ushort"),
            CriticalLowVoltage=ValueNode("CriticalLowVoltage",offset=0x0167, end=0x0168, dtype="ushort"),
            PowerOnStatus=ValueNode("PowerOnStatus",offset=0x0169, end=0x0169, dtype="uchar"),
            PowerOnMinCapacity=ValueNode("PowerOnMinCapacity",offset=0x016A, end=0x016B, dtype="ushort"),
            EstimateMidCapacityVoltage=ValueNode("EstimateMidCapacityVoltage",offset=0x016C, end=0x016D, dtype="ushort"),
            EstimateLowCapacityVoltage=ValueNode("EstimateLowCapacityVoltage",offset=0x016E, end=0x016F, dtype="ushort"),
            BatterySize=ValueNode("BatterySize",offset=0x0170, end=0x0171, dtype="short"),
            Capacity=ValueNode("Capacity",offset=0x0172, end=0x0175, dtype="long"),
            ChargeEfficency=ValueNode("ChargeEfficency",offset=0x0176, end=0x0176, dtype="uchar"),
            MaintenanceReChargeLevel=ValueNode("MaintenanceReChargeLevel",offset=0x0177, end=0x0177, dtype="uchar"),
            NotUsed002=ValueNode("NotUsed002",offset=0x0178, end=0x0178, dtype="uchar"),
            PowerOnChargingTimeout=ValueNode("PowerOnChargingTimeout",offset=0x0179, end=0x017A, dtype="ushort"),
            InitDutyCycleOnTime=ValueNode("InitDutyCycleOnTime",offset=0x017B, end=0x017C, dtype="ushort"),
            InitDutyCycleOffTime=ValueNode("InitDutyCycleOffTime",offset=0x017D, end=0x017E, dtype="ushort"),
            FastDutyCycleOnTime=ValueNode("FastDutyCycleOnTime",offset=0x017F, end=0x0180, dtype="ushort"),
            FastDutyCycleOffTime=ValueNode("FastDutyCycleOffTime",offset=0x0181, end=0x0182, dtype="ushort"),
            TopDutyCycleOnTime=ValueNode("TopDutyCycleOnTime",offset=0x0183, end=0x0184, dtype="ushort"),
            TopDutyCycleOffTime=ValueNode("TopDutyCycleOffTime",offset=0x0185, end=0x0186, dtype="ushort"),
            MaintenanceDutyCycleOnTime=ValueNode("MaintenanceDutyCycleOnTime",offset=0x0187, end=0x0188, dtype="ushort"),
            MaintenanceDutyCycleOffTime=ValueNode("MaintenanceDutyCycleOffTime",offset=0x0189, end=0x018A, dtype="ushort"),
            InitStateTimeout=ValueNode("InitStateTimeout",offset=0x018B, end=0x018C, dtype="ushort"),
            FastStateTimeout=ValueNode("FastStateTimeout",offset=0x018D, end=0x018E, dtype="ushort"),
            TopStateTimeout=ValueNode("TopStateTimeout",offset=0x018F, end=0x0190, dtype="ushort"),
            MaintenanceStateTimeout=ValueNode("MaintenanceStateTimeout",offset=0x0191, end=0x0192, dtype="ushort"),
            Percent2GotoFastCharging=ValueNode("Percent2GotoFastCharging",offset=0x0193, end=0x0193, dtype="uchar"),
            Percent2GotoTopCharging=ValueNode("Percent2GotoTopCharging",offset=0x0194, end=0x0194, dtype="uchar"),
            TicksPerSecBy100mA=ValueNode("TicksPerSecBy100mA",offset=0x0195, end=0x0196, dtype="short")
        ),
        HsBatterySettingsReseved=ValueArray("HsBatterySettingsReseved",offset=0x0197, end=0x0197, dtype="uchar"),
        PatchCodeSrcAddr=ValueNode("PatchCodeSrcAddr",offset=0x0198, end=0x0199, dtype="ushort"),
        PatchCodeDstAddr=ValueNode("PatchCodeDstAddr",offset=0x019A, end=0x019D, dtype="ulong"),
        Audio=StructNode("Audio",offset=0x019E, end=0x01DA,
            Option=ValueNode("Option",offset=0x019E, end=0x019E, dtype="uchar"),
            Earp=StructNode("Earp",offset=0x019F, end=0x01B1,
                Reserved=ValueNode("Reserved",offset=0x019F, end=0x019F, dtype="char"),
                Vol=NodeArray("Vol",offset=0x01A0, end=0x01B1, nodes=[
                    StructNode("Element 0",offset=0x01A0, end=0x01A2,
                        RxGain=ValueNode("RxGain",offset=0x01A0, end=0x01A0, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01A1, end=0x01A1, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01A2, end=0x01A2, dtype="char")
                    ),
                    StructNode("Element 1",offset=0x01A3, end=0x01A5,
                        RxGain=ValueNode("RxGain",offset=0x01A3, end=0x01A3, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01A4, end=0x01A4, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01A5, end=0x01A5, dtype="char")
                    ),
                    StructNode("Element 2",offset=0x01A6, end=0x01A8,
                        RxGain=ValueNode("RxGain",offset=0x01A6, end=0x01A6, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01A7, end=0x01A7, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01A8, end=0x01A8, dtype="char")
                    ),
                    StructNode("Element 3",offset=0x01A9, end=0x01AB,
                        RxGain=ValueNode("RxGain",offset=0x01A9, end=0x01A9, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01AA, end=0x01AA, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01AB, end=0x01AB, dtype="char")
                    ),
                    StructNode("Element 4",offset=0x01AC, end=0x01AE,
                        RxGain=ValueNode("RxGain",offset=0x01AC, end=0x01AC, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01AD, end=0x01AD, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01AE, end=0x01AE, dtype="char")
                    ),
                    StructNode("Element 5",offset=0x01AF, end=0x01B1,
                        RxGain=ValueNode("RxGain",offset=0x01AF, end=0x01AF, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01B0, end=0x01B0, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01B1, end=0x01B1, dtype="char")
                    )
                ]
                )
            ),
            Heads=StructNode("Heads",offset=0x01B2, end=0x01C4,
                Reserved=ValueNode("Reserved",offset=0x01B2, end=0x01B2, dtype="char"),
                Vol=NodeArray("Vol",offset=0x01B3, end=0x01C4, nodes=[
                    StructNode("Element 0",offset=0x01B3, end=0x01B5,
                        RxGain=ValueNode("RxGain",offset=0x01B3, end=0x01B3, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01B4, end=0x01B4, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01B5, end=0x01B5, dtype="char")
                    ),
                    StructNode("Element 1",offset=0x01B6, end=0x01B8,
                        RxGain=ValueNode("RxGain",offset=0x01B6, end=0x01B6, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01B7, end=0x01B7, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01B8, end=0x01B8, dtype="char")
                    ),
                    StructNode("Element 2",offset=0x01B9, end=0x01BB,
                        RxGain=ValueNode("RxGain",offset=0x01B9, end=0x01B9, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01BA, end=0x01BA, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01BB, end=0x01BB, dtype="char")
                    ),
                    StructNode("Element 3",offset=0x01BC, end=0x01BE,
                        RxGain=ValueNode("RxGain",offset=0x01BC, end=0x01BC, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01BD, end=0x01BD, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01BE, end=0x01BE, dtype="char")
                    ),
                    StructNode("Element 4",offset=0x01BF, end=0x01C1,
                        RxGain=ValueNode("RxGain",offset=0x01BF, end=0x01BF, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01C0, end=0x01C0, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01C1, end=0x01C1, dtype="char")
                    ),
                    StructNode("Element 5",offset=0x01C2, end=0x01C4,
                        RxGain=ValueNode("RxGain",offset=0x01C2, end=0x01C2, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01C3, end=0x01C3, dtype="char"),
                        SideToneGain=ValueNode("SideToneGain",offset=0x01C4, end=0x01C4, dtype="char")
                    )
                ]
                )
            ),
            SpkPh=StructNode("SpkPh",offset=0x01C5, end=0x01D1,
                Reserved=ValueNode("Reserved",offset=0x01C5, end=0x01C5, dtype="char"),
                Vol=NodeArray("Vol",offset=0x01C6, end=0x01D1, nodes=[
                    StructNode("Element 0",offset=0x01C6, end=0x01C7,
                        RxGain=ValueNode("RxGain",offset=0x01C6, end=0x01C6, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01C7, end=0x01C7, dtype="char")
                    ),
                    StructNode("Element 1",offset=0x01C8, end=0x01C9,
                        RxGain=ValueNode("RxGain",offset=0x01C8, end=0x01C8, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01C9, end=0x01C9, dtype="char")
                    ),
                    StructNode("Element 2",offset=0x01CA, end=0x01CB,
                        RxGain=ValueNode("RxGain",offset=0x01CA, end=0x01CA, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01CB, end=0x01CB, dtype="char")
                    ),
                    StructNode("Element 3",offset=0x01CC, end=0x01CD,
                        RxGain=ValueNode("RxGain",offset=0x01CC, end=0x01CC, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01CD, end=0x01CD, dtype="char")
                    ),
                    StructNode("Element 4",offset=0x01CE, end=0x01CF,
                        RxGain=ValueNode("RxGain",offset=0x01CE, end=0x01CE, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01CF, end=0x01CF, dtype="char")
                    ),
                    StructNode("Element 5",offset=0x01D0, end=0x01D1,
                        RxGain=ValueNode("RxGain",offset=0x01D0, end=0x01D0, dtype="char"),
                        TxGain=ValueNode("TxGain",offset=0x01D1, end=0x01D1, dtype="char")
                    )
                ]
                )
            ),
            MicMuteTime=ValueNode("MicMuteTime",offset=0x01D2, end=0x01D2, dtype="uchar"),
            CodecPowerUpTime=ValueNode("CodecPowerUpTime",offset=0x01D3, end=0x01D3, dtype="uchar"),
            CodecPowerDownTime=ValueNode("CodecPowerDownTime",offset=0x01D4, end=0x01D5, dtype="ushort"),
            CodecAnaAgcCfg=StructNode("CodecAnaAgcCfg",offset=0x01D6, end=0x01D8,
                AnaAgcCLvlMax=ValueNode("AnaAgcCLvlMax",offset=0x01D6, end=0x01D6, dtype="char"),
                AnaAgcCLvlMin=ValueNode("AnaAgcCLvlMin",offset=0x01D7, end=0x01D7, dtype="char"),
                AnaAgcMicMin=ValueNode("AnaAgcMicMin",offset=0x01D8, end=0x01D8, dtype="char")
            ),
            Reserved=ValueArray("Reserved",offset=0x01D9, end=0x01DA, dtype="ushort")
        ),
        AudioUnit=StructNode("AudioUnit",offset=0x01DB, end=0x02E9,
            Codec=StructNode("Codec",offset=0x01DB, end=0x02D1,
                Cfg=StructNode("Cfg",offset=0x01DB, end=0x01DB,
                    Flags=ValueNode("Flags",offset=0x01DB, end=0x01DB, dtype="uchar")
                ),
                NC100Hz8KhzCfg=StructNode("NC100Hz8KhzCfg",offset=0x01DC, end=0x01E1,
                    alpha=ValueNode("alpha",offset=0x01DC, end=0x01DD, dtype="ushort"),
                    beta=ValueNode("beta",offset=0x01DE, end=0x01DF, dtype="ushort"),
                    threshold=ValueNode("threshold",offset=0x01E0, end=0x01E1, dtype="ushort")
                ),
                NC100Hz16KhzCfg=StructNode("NC100Hz16KhzCfg",offset=0x01E2, end=0x01E7,
                    alpha=ValueNode("alpha",offset=0x01E2, end=0x01E3, dtype="ushort"),
                    beta=ValueNode("beta",offset=0x01E4, end=0x01E5, dtype="ushort"),
                    threshold=ValueNode("threshold",offset=0x01E6, end=0x01E7, dtype="ushort")
                ),
                Set_8Khz=StructNode("Set_8Khz",offset=0x01E8, end=0x0257,
                    SpkFilt_Earp=StructNode("SpkFilt_Earp",offset=0x01E8, end=0x0203,
                        PFilt1=StructNode("PFilt1",offset=0x01E8, end=0x01F5,
                            C0=ValueNode("C0",offset=0x01E8, end=0x01E9, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x01EA, end=0x01EB, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x01EC, end=0x01ED, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x01EE, end=0x01EF, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x01F0, end=0x01F1, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x01F2, end=0x01F3, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x01F4, end=0x01F5, dtype="ushort")
                        ),
                        PFilt2=StructNode("PFilt2",offset=0x01F6, end=0x0203,
                            C0=ValueNode("C0",offset=0x01F6, end=0x01F7, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x01F8, end=0x01F9, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x01FA, end=0x01FB, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x01FC, end=0x01FD, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x01FE, end=0x01FF, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x0200, end=0x0201, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x0202, end=0x0203, dtype="ushort")
                        )
                    ),
                    SpkFilt_Headset=StructNode("SpkFilt_Headset",offset=0x0204, end=0x021F,
                        PFilt1=StructNode("PFilt1",offset=0x0204, end=0x0211,
                            C0=ValueNode("C0",offset=0x0204, end=0x0205, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x0206, end=0x0207, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x0208, end=0x0209, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x020A, end=0x020B, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x020C, end=0x020D, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x020E, end=0x020F, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x0210, end=0x0211, dtype="ushort")
                        ),
                        PFilt2=StructNode("PFilt2",offset=0x0212, end=0x021F,
                            C0=ValueNode("C0",offset=0x0212, end=0x0213, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x0214, end=0x0215, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x0216, end=0x0217, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x0218, end=0x0219, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x021A, end=0x021B, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x021C, end=0x021D, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x021E, end=0x021F, dtype="ushort")
                        )
                    ),
                    SpkFilt_SpkPh=StructNode("SpkFilt_SpkPh",offset=0x0220, end=0x023B,
                        PFilt1=StructNode("PFilt1",offset=0x0220, end=0x022D,
                            C0=ValueNode("C0",offset=0x0220, end=0x0221, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x0222, end=0x0223, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x0224, end=0x0225, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x0226, end=0x0227, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x0228, end=0x0229, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x022A, end=0x022B, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x022C, end=0x022D, dtype="ushort")
                        ),
                        PFilt2=StructNode("PFilt2",offset=0x022E, end=0x023B,
                            C0=ValueNode("C0",offset=0x022E, end=0x022F, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x0230, end=0x0231, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x0232, end=0x0233, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x0234, end=0x0235, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x0236, end=0x0237, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x0238, end=0x0239, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x023A, end=0x023B, dtype="ushort")
                        )
                    ),
                    MicFilt=StructNode("MicFilt",offset=0x023C, end=0x0257,
                        PFilt3=StructNode("PFilt3",offset=0x023C, end=0x0249,
                            C0=ValueNode("C0",offset=0x023C, end=0x023D, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x023E, end=0x023F, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x0240, end=0x0241, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x0242, end=0x0243, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x0244, end=0x0245, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x0246, end=0x0247, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x0248, end=0x0249, dtype="ushort")
                        ),
                        PFilt4=StructNode("PFilt4",offset=0x024A, end=0x0257,
                            C0=ValueNode("C0",offset=0x024A, end=0x024B, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x024C, end=0x024D, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x024E, end=0x024F, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x0250, end=0x0251, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x0252, end=0x0253, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x0254, end=0x0255, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x0256, end=0x0257, dtype="ushort")
                        )
                    )
                ),
                Set_16Khz=StructNode("Set_16Khz",offset=0x0258, end=0x02C7,
                    SpkFilt_Earp=StructNode("SpkFilt_Earp",offset=0x0258, end=0x0273,
                        PFilt1=StructNode("PFilt1",offset=0x0258, end=0x0265,
                            C0=ValueNode("C0",offset=0x0258, end=0x0259, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x025A, end=0x025B, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x025C, end=0x025D, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x025E, end=0x025F, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x0260, end=0x0261, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x0262, end=0x0263, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x0264, end=0x0265, dtype="ushort")
                        ),
                        PFilt2=StructNode("PFilt2",offset=0x0266, end=0x0273,
                            C0=ValueNode("C0",offset=0x0266, end=0x0267, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x0268, end=0x0269, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x026A, end=0x026B, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x026C, end=0x026D, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x026E, end=0x026F, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x0270, end=0x0271, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x0272, end=0x0273, dtype="ushort")
                        )
                    ),
                    SpkFilt_Headset=StructNode("SpkFilt_Headset",offset=0x0274, end=0x028F,
                        PFilt1=StructNode("PFilt1",offset=0x0274, end=0x0281,
                            C0=ValueNode("C0",offset=0x0274, end=0x0275, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x0276, end=0x0277, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x0278, end=0x0279, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x027A, end=0x027B, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x027C, end=0x027D, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x027E, end=0x027F, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x0280, end=0x0281, dtype="ushort")
                        ),
                        PFilt2=StructNode("PFilt2",offset=0x0282, end=0x028F,
                            C0=ValueNode("C0",offset=0x0282, end=0x0283, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x0284, end=0x0285, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x0286, end=0x0287, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x0288, end=0x0289, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x028A, end=0x028B, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x028C, end=0x028D, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x028E, end=0x028F, dtype="ushort")
                        )
                    ),
                    SpkFilt_SpkPh=StructNode("SpkFilt_SpkPh",offset=0x0290, end=0x02AB,
                        PFilt1=StructNode("PFilt1",offset=0x0290, end=0x029D,
                            C0=ValueNode("C0",offset=0x0290, end=0x0291, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x0292, end=0x0293, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x0294, end=0x0295, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x0296, end=0x0297, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x0298, end=0x0299, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x029A, end=0x029B, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x029C, end=0x029D, dtype="ushort")
                        ),
                        PFilt2=StructNode("PFilt2",offset=0x029E, end=0x02AB,
                            C0=ValueNode("C0",offset=0x029E, end=0x029F, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x02A0, end=0x02A1, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x02A2, end=0x02A3, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x02A4, end=0x02A5, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x02A6, end=0x02A7, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x02A8, end=0x02A9, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x02AA, end=0x02AB, dtype="ushort")
                        )
                    ),
                    MicFilt=StructNode("MicFilt",offset=0x02AC, end=0x02C7,
                        PFilt3=StructNode("PFilt3",offset=0x02AC, end=0x02B9,
                            C0=ValueNode("C0",offset=0x02AC, end=0x02AD, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x02AE, end=0x02AF, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x02B0, end=0x02B1, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x02B2, end=0x02B3, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x02B4, end=0x02B5, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x02B6, end=0x02B7, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x02B8, end=0x02B9, dtype="ushort")
                        ),
                        PFilt4=StructNode("PFilt4",offset=0x02BA, end=0x02C7,
                            C0=ValueNode("C0",offset=0x02BA, end=0x02BB, dtype="ushort"),
                            C1=ValueNode("C1",offset=0x02BC, end=0x02BD, dtype="ushort"),
                            C2=ValueNode("C2",offset=0x02BE, end=0x02BF, dtype="ushort"),
                            C3=ValueNode("C3",offset=0x02C0, end=0x02C1, dtype="ushort"),
                            C4=ValueNode("C4",offset=0x02C2, end=0x02C3, dtype="ushort"),
                            Fin_Att=ValueNode("Fin_Att",offset=0x02C4, end=0x02C5, dtype="ushort"),
                            Foutgains=ValueNode("Foutgains",offset=0x02C6, end=0x02C7, dtype="ushort")
                        )
                    )
                ),
                VolCtrlCfg=StructNode("VolCtrlCfg",offset=0x02C8, end=0x02CD,
                    AgcThresholdLvl=ValueNode("AgcThresholdLvl",offset=0x02C8, end=0x02C9, dtype="ushort"),
                    Supp_centclip_att=ValueNode("Supp_centclip_att",offset=0x02CA, end=0x02CB, dtype="ushort"),
                    Supp_centclip=ValueNode("Supp_centclip",offset=0x02CC, end=0x02CD, dtype="ushort")
                ),
                MicPostCfg=StructNode("MicPostCfg",offset=0x02CE, end=0x02D1,
                    Supp_centclip_att=ValueNode("Supp_centclip_att",offset=0x02CE, end=0x02CF, dtype="ushort"),
                    Supp_centclip=ValueNode("Supp_centclip",offset=0x02D0, end=0x02D1, dtype="ushort")
                )
            ),
            ReservedHfree=ValueArray("ReservedHfree",offset=0x02D2, end=0x02DC, dtype="uchar"),
            Reserved0=StructNode("Reserved0",offset=0x02DD, end=0x02E2,
                Data1=ValueNode("Data1",offset=0x02DD, end=0x02DE, dtype="ushort"),
                Data2=ValueNode("Data2",offset=0x02DF, end=0x02E0, dtype="ushort"),
                Data3=ValueNode("Data3",offset=0x02E1, end=0x02E2, dtype="ushort")
            ),
            Reservedb=ValueNode("Reservedb",offset=0x02E3, end=0x02E3, dtype="uchar"),
            Reserved=ValueArray("Reserved",offset=0x02E4, end=0x02E9, dtype="ushort")
        ),
        AudioUnitPaec=StructNode("AudioUnitPaec",offset=0x02EA, end=0x0313,
            Paec=StructNode("Paec",offset=0x02EA, end=0x0313,
                PaecCfg_8kHz=StructNode("PaecCfg_8kHz",offset=0x02EA, end=0x02F1,
                    cctc=ValueNode("cctc",offset=0x02EA, end=0x02EB, dtype="ushort"),
                    smoothdef=ValueNode("smoothdef",offset=0x02EC, end=0x02ED, dtype="ushort"),
                    smoothlow=ValueNode("smoothlow",offset=0x02EE, end=0x02EF, dtype="ushort"),
                    smoothtop=ValueNode("smoothtop",offset=0x02F0, end=0x02F1, dtype="ushort")
                ),
                PaecCfg_16kHz=StructNode("PaecCfg_16kHz",offset=0x02F2, end=0x02F9,
                    cctc=ValueNode("cctc",offset=0x02F2, end=0x02F3, dtype="ushort"),
                    smoothdef=ValueNode("smoothdef",offset=0x02F4, end=0x02F5, dtype="ushort"),
                    smoothlow=ValueNode("smoothlow",offset=0x02F6, end=0x02F7, dtype="ushort"),
                    smoothtop=ValueNode("smoothtop",offset=0x02F8, end=0x02F9, dtype="ushort")
                ),
                PaecCfg=StructNode("PaecCfg",offset=0x02FA, end=0x0313,
                    init=ValueNode("init",offset=0x02FA, end=0x02FB, dtype="ushort"),
                    noiseestgainshft=ValueNode("noiseestgainshft",offset=0x02FC, end=0x02FD, dtype="ushort"),
                    noiseestspkgainshft=ValueNode("noiseestspkgainshft",offset=0x02FE, end=0x02FF, dtype="ushort"),
                    gamma=ValueNode("gamma",offset=0x0300, end=0x0301, dtype="ushort"),
                    beta=ValueNode("beta",offset=0x0302, end=0x0303, dtype="ushort"),
                    attlimit=ValueNode("attlimit",offset=0x0304, end=0x0305, dtype="ushort"),
                    noiseattlimit=ValueNode("noiseattlimit",offset=0x0306, end=0x0307, dtype="ushort"),
                    retainnoisethr1div=ValueNode("retainnoisethr1div",offset=0x0308, end=0x0309, dtype="ushort"),
                    attlimitthr1div=ValueNode("attlimitthr1div",offset=0x030A, end=0x030B, dtype="ushort"),
                    smooththr=ValueNode("smooththr",offset=0x030C, end=0x030D, dtype="ushort"),
                    extra_shift=ValueNode("extra_shift",offset=0x030E, end=0x030F, dtype="ushort"),
                    intshift_maxnorm=ValueNode("intshift_maxnorm",offset=0x0310, end=0x0311, dtype="ushort"),
                    post_txgain=ValueNode("post_txgain",offset=0x0312, end=0x0312, dtype="char"),
                    pre_txgain=ValueNode("pre_txgain",offset=0x0313, end=0x0313, dtype="char")
                )
            )
        ),
        Subs0=StructNode("Subs0",offset=0x0314, end=0x033A,
            RFPI=ValueArray("RFPI",offset=0x0314, end=0x0318, dtype="uchar"),
            ServiceClass=ValueNode("ServiceClass",offset=0x0319, end=0x0319, dtype="uchar"),
            LAL=ValueNode("LAL",offset=0x031A, end=0x031A, dtype="uchar"),
            IpuiLen=ValueNode("IpuiLen",offset=0x031B, end=0x031B, dtype="uchar"),
            IPUI=ValueArray("IPUI",offset=0x031C, end=0x0328, dtype="uchar"),
            ZAP=ValueNode("ZAP",offset=0x0329, end=0x0329, dtype="uchar"),
            Status=ValueNode("Status",offset=0x032A, end=0x032A, dtype="uchar"),
            UAK=ValueArray("UAK",offset=0x032B, end=0x033A, dtype="uchar")
        ),
        Subs1=StructNode("Subs1",offset=0x033B, end=0x0361,
            RFPI=ValueArray("RFPI",offset=0x033B, end=0x033F, dtype="uchar"),
            ServiceClass=ValueNode("ServiceClass",offset=0x0340, end=0x0340, dtype="uchar"),
            LAL=ValueNode("LAL",offset=0x0341, end=0x0341, dtype="uchar"),
            IpuiLen=ValueNode("IpuiLen",offset=0x0342, end=0x0342, dtype="uchar"),
            IPUI=ValueArray("IPUI",offset=0x0343, end=0x034F, dtype="uchar"),
            ZAP=ValueNode("ZAP",offset=0x0350, end=0x0350, dtype="uchar"),
            Status=ValueNode("Status",offset=0x0351, end=0x0351, dtype="uchar"),
            UAK=ValueArray("UAK",offset=0x0352, end=0x0361, dtype="uchar")
        ),
        Subs2=StructNode("Subs2",offset=0x0362, end=0x0388,
            RFPI=ValueArray("RFPI",offset=0x0362, end=0x0366, dtype="uchar"),
            ServiceClass=ValueNode("ServiceClass",offset=0x0367, end=0x0367, dtype="uchar"),
            LAL=ValueNode("LAL",offset=0x0368, end=0x0368, dtype="uchar"),
            IpuiLen=ValueNode("IpuiLen",offset=0x0369, end=0x0369, dtype="uchar"),
            IPUI=ValueArray("IPUI",offset=0x036A, end=0x0376, dtype="uchar"),
            ZAP=ValueNode("ZAP",offset=0x0377, end=0x0377, dtype="uchar"),
            Status=ValueNode("Status",offset=0x0378, end=0x0378, dtype="uchar"),
            UAK=ValueArray("UAK",offset=0x0379, end=0x0388, dtype="uchar")
        ),
        Subs3=StructNode("Subs3",offset=0x0389, end=0x03AF,
            RFPI=ValueArray("RFPI",offset=0x0389, end=0x038D, dtype="uchar"),
            ServiceClass=ValueNode("ServiceClass",offset=0x038E, end=0x038E, dtype="uchar"),
            LAL=ValueNode("LAL",offset=0x038F, end=0x038F, dtype="uchar"),
            IpuiLen=ValueNode("IpuiLen",offset=0x0390, end=0x0390, dtype="uchar"),
            IPUI=ValueArray("IPUI",offset=0x0391, end=0x039D, dtype="uchar"),
            ZAP=ValueNode("ZAP",offset=0x039E, end=0x039E, dtype="uchar"),
            Status=ValueNode("Status",offset=0x039F, end=0x039F, dtype="uchar"),
            UAK=ValueArray("UAK",offset=0x03A0, end=0x03AF, dtype="uchar")
        ),
        FwuMode=ValueNode("FwuMode",offset=0x03B0, end=0x03B0, dtype="uchar"),
        CustomFixes=ValueNode("CustomFixes",offset=0x03B1, end=0x03B1, dtype="uchar"),
        EepromDrvId=ValueNode("EepromDrvId",offset=0x03B2, end=0x03B2, dtype="uchar"),
        Cola=ValueArray("Cola",offset=0x03B3, end=0x04B2, dtype="uchar"),
        SpiReserved=ValueNode("SpiReserved",offset=0x04B3, end=0x04B3, dtype="uchar"),
        SpiMode=ValueNode("SpiMode",offset=0x04B4, end=0x04B4, dtype="uchar"),
        SpiDoIdleState=ValueNode("SpiDoIdleState",offset=0x04B5, end=0x04B5, dtype="uchar"),
        SpiEnCtrl=ValueNode("SpiEnCtrl",offset=0x04B6, end=0x04B6, dtype="uchar"),
        SpiIntActiveValue=ValueNode("SpiIntActiveValue",offset=0x04B7, end=0x04B7, dtype="uchar"),
        SpiClock=ValueNode("SpiClock",offset=0x04B8, end=0x04B8, dtype="uchar"),
        bEnrollStatusFlags=ValueArray("bEnrollStatusFlags",offset=0x04B9, end=0x04BC, dtype="uchar"),
        MmiRingerMelody=ValueNode("MmiRingerMelody",offset=0x04BD, end=0x04BD, dtype="uchar"),
        MmiRingerVolume=ValueNode("MmiRingerVolume",offset=0x04BE, end=0x04BE, dtype="uchar"),
        PortBackdriveProtection=ValueNode("PortBackdriveProtection",offset=0x04BF, end=0x04BF, dtype="uchar"),
        ActiveRegistration=ValueNode("ActiveRegistration",offset=0x04C0, end=0x04C0, dtype="uchar"),
        PpEnrolledBases=NodeArray("PpEnrolledBases",offset=0x04C1, end=0x04F0, nodes=[
            StructNode("Element 0",offset=0x04C1, end=0x04CC,
                PpHsNo=ValueNode("PpHsNo",offset=0x04C1, end=0x04C1, dtype="uchar"),
                IsKnownBase=ValueNode("IsKnownBase",offset=0x04C2, end=0x04C2, dtype="uchar"),
                CodecList=StructNode("CodecList",offset=0x04C3, end=0x04CC,
                    NegotiationIndicator=ValueNode("NegotiationIndicator",offset=0x04C3, end=0x04C3, dtype="uchar"),
                    NoOfCodecEntries=ValueNode("NoOfCodecEntries",offset=0x04C4, end=0x04C4, dtype="uchar"),
                    CodecInfo=NodeArray("CodecInfo",offset=0x04C5, end=0x04CC, nodes=[
                        StructNode("Element 0",offset=0x04C5, end=0x04C8,
                            Codec=ValueNode("Codec",offset=0x04C5, end=0x04C5, dtype="uchar"),
                            MacDlcService=ValueNode("MacDlcService",offset=0x04C6, end=0x04C6, dtype="uchar"),
                            CplaneRouting=ValueNode("CplaneRouting",offset=0x04C7, end=0x04C7, dtype="uchar"),
                            SlotSize=ValueNode("SlotSize",offset=0x04C8, end=0x04C8, dtype="uchar")
                        ),
                        StructNode("Element 1",offset=0x04C9, end=0x04CC,
                            Codec=ValueNode("Codec",offset=0x04C9, end=0x04C9, dtype="uchar"),
                            MacDlcService=ValueNode("MacDlcService",offset=0x04CA, end=0x04CA, dtype="uchar"),
                            CplaneRouting=ValueNode("CplaneRouting",offset=0x04CB, end=0x04CB, dtype="uchar"),
                            SlotSize=ValueNode("SlotSize",offset=0x04CC, end=0x04CC, dtype="uchar")
                        )
                    ]
                    )
                )
            ),
            StructNode("Element 1",offset=0x04CD, end=0x04D8,
                PpHsNo=ValueNode("PpHsNo",offset=0x04CD, end=0x04CD, dtype="uchar"),
                IsKnownBase=ValueNode("IsKnownBase",offset=0x04CE, end=0x04CE, dtype="uchar"),
                CodecList=StructNode("CodecList",offset=0x04CF, end=0x04D8,
                    NegotiationIndicator=ValueNode("NegotiationIndicator",offset=0x04CF, end=0x04CF, dtype="uchar"),
                    NoOfCodecEntries=ValueNode("NoOfCodecEntries",offset=0x04D0, end=0x04D0, dtype="uchar"),
                    CodecInfo=NodeArray("CodecInfo",offset=0x04D1, end=0x04D8, nodes=[
                        StructNode("Element 0",offset=0x04D1, end=0x04D4,
                            Codec=ValueNode("Codec",offset=0x04D1, end=0x04D1, dtype="uchar"),
                            MacDlcService=ValueNode("MacDlcService",offset=0x04D2, end=0x04D2, dtype="uchar"),
                            CplaneRouting=ValueNode("CplaneRouting",offset=0x04D3, end=0x04D3, dtype="uchar"),
                            SlotSize=ValueNode("SlotSize",offset=0x04D4, end=0x04D4, dtype="uchar")
                        ),
                        StructNode("Element 1",offset=0x04D5, end=0x04D8,
                            Codec=ValueNode("Codec",offset=0x04D5, end=0x04D5, dtype="uchar"),
                            MacDlcService=ValueNode("MacDlcService",offset=0x04D6, end=0x04D6, dtype="uchar"),
                            CplaneRouting=ValueNode("CplaneRouting",offset=0x04D7, end=0x04D7, dtype="uchar"),
                            SlotSize=ValueNode("SlotSize",offset=0x04D8, end=0x04D8, dtype="uchar")
                        )
                    ]
                    )
                )
            ),
            StructNode("Element 2",offset=0x04D9, end=0x04E4,
                PpHsNo=ValueNode("PpHsNo",offset=0x04D9, end=0x04D9, dtype="uchar"),
                IsKnownBase=ValueNode("IsKnownBase",offset=0x04DA, end=0x04DA, dtype="uchar"),
                CodecList=StructNode("CodecList",offset=0x04DB, end=0x04E4,
                    NegotiationIndicator=ValueNode("NegotiationIndicator",offset=0x04DB, end=0x04DB, dtype="uchar"),
                    NoOfCodecEntries=ValueNode("NoOfCodecEntries",offset=0x04DC, end=0x04DC, dtype="uchar"),
                    CodecInfo=NodeArray("CodecInfo",offset=0x04DD, end=0x04E4, nodes=[
                        StructNode("Element 0",offset=0x04DD, end=0x04E0,
                            Codec=ValueNode("Codec",offset=0x04DD, end=0x04DD, dtype="uchar"),
                            MacDlcService=ValueNode("MacDlcService",offset=0x04DE, end=0x04DE, dtype="uchar"),
                            CplaneRouting=ValueNode("CplaneRouting",offset=0x04DF, end=0x04DF, dtype="uchar"),
                            SlotSize=ValueNode("SlotSize",offset=0x04E0, end=0x04E0, dtype="uchar")
                        ),
                        StructNode("Element 1",offset=0x04E1, end=0x04E4,
                            Codec=ValueNode("Codec",offset=0x04E1, end=0x04E1, dtype="uchar"),
                            MacDlcService=ValueNode("MacDlcService",offset=0x04E2, end=0x04E2, dtype="uchar"),
                            CplaneRouting=ValueNode("CplaneRouting",offset=0x04E3, end=0x04E3, dtype="uchar"),
                            SlotSize=ValueNode("SlotSize",offset=0x04E4, end=0x04E4, dtype="uchar")
                        )
                    ]
                    )
                )
            ),
            StructNode("Element 3",offset=0x04E5, end=0x04F0,
                PpHsNo=ValueNode("PpHsNo",offset=0x04E5, end=0x04E5, dtype="uchar"),
                IsKnownBase=ValueNode("IsKnownBase",offset=0x04E6, end=0x04E6, dtype="uchar"),
                CodecList=StructNode("CodecList",offset=0x04E7, end=0x04F0,
                    NegotiationIndicator=ValueNode("NegotiationIndicator",offset=0x04E7, end=0x04E7, dtype="uchar"),
                    NoOfCodecEntries=ValueNode("NoOfCodecEntries",offset=0x04E8, end=0x04E8, dtype="uchar"),
                    CodecInfo=NodeArray("CodecInfo",offset=0x04E9, end=0x04F0, nodes=[
                        StructNode("Element 0",offset=0x04E9, end=0x04EC,
                            Codec=ValueNode("Codec",offset=0x04E9, end=0x04E9, dtype="uchar"),
                            MacDlcService=ValueNode("MacDlcService",offset=0x04EA, end=0x04EA, dtype="uchar"),
                            CplaneRouting=ValueNode("CplaneRouting",offset=0x04EB, end=0x04EB, dtype="uchar"),
                            SlotSize=ValueNode("SlotSize",offset=0x04EC, end=0x04EC, dtype="uchar")
                        ),
                        StructNode("Element 1",offset=0x04ED, end=0x04F0,
                            Codec=ValueNode("Codec",offset=0x04ED, end=0x04ED, dtype="uchar"),
                            MacDlcService=ValueNode("MacDlcService",offset=0x04EE, end=0x04EE, dtype="uchar"),
                            CplaneRouting=ValueNode("CplaneRouting",offset=0x04EF, end=0x04EF, dtype="uchar"),
                            SlotSize=ValueNode("SlotSize",offset=0x04F0, end=0x04F0, dtype="uchar")
                        )
                    ]
                    )
                )
            )
        ]
        ),
        CodecTypeForOutgoingCall=ValueNode("CodecTypeForOutgoingCall",offset=0x04F1, end=0x04F1, dtype="uchar"),
        LineNoOutgoingCall=ValueNode("LineNoOutgoingCall",offset=0x04F2, end=0x04F2, dtype="uchar"),
        EarlyEncryptionKeyArr=NodeArray("EarlyEncryptionKeyArr",offset=0x04F3, end=0x051A, nodes=[
            StructNode("Element 0",offset=0x04F3, end=0x04FC,
                DefaultCipkerKeyIndexMsb=ValueNode("DefaultCipkerKeyIndexMsb",offset=0x04F3, end=0x04F3, dtype="uchar"),
                DefaultCipkerKeyIndexLsb=ValueNode("DefaultCipkerKeyIndexLsb",offset=0x04F4, end=0x04F4, dtype="uchar"),
                DefaultCipkerKeyArr=ValueArray("DefaultCipkerKeyArr",offset=0x04F5, end=0x04FC, dtype="uchar")
            ),
            StructNode("Element 1",offset=0x04FD, end=0x0506,
                DefaultCipkerKeyIndexMsb=ValueNode("DefaultCipkerKeyIndexMsb",offset=0x04FD, end=0x04FD, dtype="uchar"),
                DefaultCipkerKeyIndexLsb=ValueNode("DefaultCipkerKeyIndexLsb",offset=0x04FE, end=0x04FE, dtype="uchar"),
                DefaultCipkerKeyArr=ValueArray("DefaultCipkerKeyArr",offset=0x04FF, end=0x0506, dtype="uchar")
            ),
            StructNode("Element 2",offset=0x0507, end=0x0510,
                DefaultCipkerKeyIndexMsb=ValueNode("DefaultCipkerKeyIndexMsb",offset=0x0507, end=0x0507, dtype="uchar"),
                DefaultCipkerKeyIndexLsb=ValueNode("DefaultCipkerKeyIndexLsb",offset=0x0508, end=0x0508, dtype="uchar"),
                DefaultCipkerKeyArr=ValueArray("DefaultCipkerKeyArr",offset=0x0509, end=0x0510, dtype="uchar")
            ),
            StructNode("Element 3",offset=0x0511, end=0x051A,
                DefaultCipkerKeyIndexMsb=ValueNode("DefaultCipkerKeyIndexMsb",offset=0x0511, end=0x0511, dtype="uchar"),
                DefaultCipkerKeyIndexLsb=ValueNode("DefaultCipkerKeyIndexLsb",offset=0x0512, end=0x0512, dtype="uchar"),
                DefaultCipkerKeyArr=ValueArray("DefaultCipkerKeyArr",offset=0x0513, end=0x051A, dtype="uchar")
            )
        ]
        ),
        SclMode=ValueNode("SclMode",offset=0x051B, end=0x051B, dtype="uchar"),
        SclInterval=ValueNode("SclInterval",offset=0x051C, end=0x051C, dtype="uchar"),
        SclGuid=ValueArray("SclGuid",offset=0x051D, end=0x052C, dtype="uchar"),
        SclCommand=ValueNode("SclCommand",offset=0x052D, end=0x052D, dtype="uchar"),
        SclFileNr=ValueNode("SclFileNr",offset=0x052E, end=0x052E, dtype="uchar"),
        SclStamp=ValueNode("SclStamp",offset=0x052F, end=0x0532, dtype="ulong"),
        SclPos=ValueNode("SclPos",offset=0x0533, end=0x0536, dtype="ulong"),
        SclAddress=ValueNode("SclAddress",offset=0x0537, end=0x053A, dtype="ulong"),
        SclUrl=ValueArray("SclUrl",offset=0x053B, end=0x0576, dtype="uchar"),
        Audio2=StructNode("Audio2",offset=0x0577, end=0x05B8,
            FeCfg=StructNode("FeCfg",offset=0x0577, end=0x057C,
                Earpiece=StructNode("Earpiece",offset=0x0577, end=0x0578,
                    LsrMode=ValueNode("LsrMode",offset=0x0577, end=0x0577, dtype="uchar"),
                    MicMode=ValueNode("MicMode",offset=0x0578, end=0x0578, dtype="uchar")
                ),
                Handsfree=StructNode("Handsfree",offset=0x0579, end=0x057A,
                    LsrMode=ValueNode("LsrMode",offset=0x0579, end=0x0579, dtype="uchar"),
                    MicMode=ValueNode("MicMode",offset=0x057A, end=0x057A, dtype="uchar")
                ),
                Headset=StructNode("Headset",offset=0x057B, end=0x057C,
                    LsrMode=ValueNode("LsrMode",offset=0x057B, end=0x057B, dtype="uchar"),
                    MicMode=ValueNode("MicMode",offset=0x057C, end=0x057C, dtype="uchar")
                )
            ),
            VolOffsetNB=StructNode("VolOffsetNB",offset=0x057D, end=0x057F,
                RxGain=ValueNode("RxGain",offset=0x057D, end=0x057D, dtype="char"),
                TxGain=ValueNode("TxGain",offset=0x057E, end=0x057E, dtype="char"),
                SideToneGain=ValueNode("SideToneGain",offset=0x057F, end=0x057F, dtype="char")
            ),
            VolOffsetWB=StructNode("VolOffsetWB",offset=0x0580, end=0x0582,
                RxGain=ValueNode("RxGain",offset=0x0580, end=0x0580, dtype="char"),
                TxGain=ValueNode("TxGain",offset=0x0581, end=0x0581, dtype="char"),
                SideToneGain=ValueNode("SideToneGain",offset=0x0582, end=0x0582, dtype="char")
            ),
            MicProdOffset=ValueNode("MicProdOffset",offset=0x0583, end=0x0583, dtype="char"),
            LsrDigiGainBias=ValueNode("LsrDigiGainBias",offset=0x0584, end=0x0584, dtype="char"),
            LsrAnalogAttLimit=ValueNode("LsrAnalogAttLimit",offset=0x0585, end=0x0585, dtype="char"),
            ClassDCfg=ValueNode("ClassDCfg",offset=0x0586, end=0x0586, dtype="uchar"),
            Reserved=ValueArray("Reserved",offset=0x0587, end=0x05B8, dtype="uchar")
        ),
        HeadsetCtrl=StructNode("HeadsetCtrl",offset=0x05B9, end=0x05BE,
            ThresholdIdle=ValueNode("ThresholdIdle",offset=0x05B9, end=0x05BA, dtype="ushort"),
            ThresholdHook=ValueNode("ThresholdHook",offset=0x05BB, end=0x05BC, dtype="ushort"),
            ThresholdInCall=ValueNode("ThresholdInCall",offset=0x05BD, end=0x05BE, dtype="ushort")
        ),
        Audio3=StructNode("Audio3",offset=0x05BF, end=0x0686,
            ReservedNoiseGate=ValueArray("ReservedNoiseGate",offset=0x05BF, end=0x05E2, dtype="uchar"),
            AudioUnit=StructNode("AudioUnit",offset=0x05E3, end=0x062E,
                EcUnit=StructNode("EcUnit",offset=0x05E3, end=0x062E,
                    Supp_8khz=StructNode("Supp_8khz",offset=0x05E3, end=0x05EE,
                        Supp_Off=ValueNode("Supp_Off",offset=0x05E3, end=0x05E4, dtype="ushort"),
                        Supp_On=ValueNode("Supp_On",offset=0x05E5, end=0x05E6, dtype="ushort"),
                        CentClip_att=ValueNode("CentClip_att",offset=0x05E7, end=0x05E8, dtype="ushort"),
                        CentClip=ValueNode("CentClip",offset=0x05E9, end=0x05EA, dtype="ushort"),
                        Reserved=ValueArray("Reserved",offset=0x05EB, end=0x05EE, dtype="ushort")
                    ),
                    Lec_8khz=StructNode("Lec_8khz",offset=0x05EF, end=0x0608,
                        LecRatio0=ValueNode("LecRatio0",offset=0x05EF, end=0x05F0, dtype="ushort"),
                        LecRatio2=ValueNode("LecRatio2",offset=0x05F1, end=0x05F2, dtype="ushort"),
                        LecThrLvl1=ValueNode("LecThrLvl1",offset=0x05F3, end=0x05F4, dtype="ushort"),
                        LecThrLvl2=ValueNode("LecThrLvl2",offset=0x05F5, end=0x05F6, dtype="ushort"),
                        LecThrLvl3=ValueNode("LecThrLvl3",offset=0x05F7, end=0x05F8, dtype="ushort"),
                        LecU0=ValueNode("LecU0",offset=0x05F9, end=0x05FA, dtype="ushort"),
                        LecU1=ValueNode("LecU1",offset=0x05FB, end=0x05FC, dtype="ushort"),
                        LecU2=ValueNode("LecU2",offset=0x05FD, end=0x05FE, dtype="ushort"),
                        LecU3=ValueNode("LecU3",offset=0x05FF, end=0x0600, dtype="ushort"),
                        Gains=ValueNode("Gains",offset=0x0601, end=0x0602, dtype="ushort"),
                        rxin_att=ValueNode("rxin_att",offset=0x0603, end=0x0604, dtype="ushort"),
                        LecC1=ValueNode("LecC1",offset=0x0605, end=0x0606, dtype="ushort"),
                        NrTaps=ValueNode("NrTaps",offset=0x0607, end=0x0608, dtype="ushort")
                    ),
                    Supp_16khz=StructNode("Supp_16khz",offset=0x0609, end=0x0614,
                        Supp_Off=ValueNode("Supp_Off",offset=0x0609, end=0x060A, dtype="ushort"),
                        Supp_On=ValueNode("Supp_On",offset=0x060B, end=0x060C, dtype="ushort"),
                        CentClip_att=ValueNode("CentClip_att",offset=0x060D, end=0x060E, dtype="ushort"),
                        CentClip=ValueNode("CentClip",offset=0x060F, end=0x0610, dtype="ushort"),
                        Reserved=ValueArray("Reserved",offset=0x0611, end=0x0614, dtype="ushort")
                    ),
                    Lec_16khz=StructNode("Lec_16khz",offset=0x0615, end=0x062E,
                        LecRatio0=ValueNode("LecRatio0",offset=0x0615, end=0x0616, dtype="ushort"),
                        LecRatio2=ValueNode("LecRatio2",offset=0x0617, end=0x0618, dtype="ushort"),
                        LecThrLvl1=ValueNode("LecThrLvl1",offset=0x0619, end=0x061A, dtype="ushort"),
                        LecThrLvl2=ValueNode("LecThrLvl2",offset=0x061B, end=0x061C, dtype="ushort"),
                        LecThrLvl3=ValueNode("LecThrLvl3",offset=0x061D, end=0x061E, dtype="ushort"),
                        LecU0=ValueNode("LecU0",offset=0x061F, end=0x0620, dtype="ushort"),
                        LecU1=ValueNode("LecU1",offset=0x0621, end=0x0622, dtype="ushort"),
                        LecU2=ValueNode("LecU2",offset=0x0623, end=0x0624, dtype="ushort"),
                        LecU3=ValueNode("LecU3",offset=0x0625, end=0x0626, dtype="ushort"),
                        Gains=ValueNode("Gains",offset=0x0627, end=0x0628, dtype="ushort"),
                        rxin_att=ValueNode("rxin_att",offset=0x0629, end=0x062A, dtype="ushort"),
                        LecC1=ValueNode("LecC1",offset=0x062B, end=0x062C, dtype="ushort"),
                        NrTaps=ValueNode("NrTaps",offset=0x062D, end=0x062E, dtype="ushort")
                    )
                )
            ),
            Reserved=ValueArray("Reserved",offset=0x062F, end=0x0686, dtype="uchar")
        ),
        bRssiLevel_UpperThreshold_US=ValueNode("bRssiLevel_UpperThreshold_US",offset=0x0687, end=0x0687, dtype="uchar"),
        bRssiLevel_LowerThreshold_US=ValueNode("bRssiLevel_LowerThreshold_US",offset=0x0688, end=0x0688, dtype="uchar"),
        bRssiLevel_UpperThreshold_Japan=ValueNode("bRssiLevel_UpperThreshold_Japan",offset=0x0689, end=0x0689, dtype="uchar"),
        bRssiLevel_LowerThreshold_Japan=ValueNode("bRssiLevel_LowerThreshold_Japan",offset=0x068A, end=0x068A, dtype="uchar"),
        Unused_Byte2=ValueArray("Unused_Byte2",offset=0x068B, end=0x0FFF, dtype="uchar")
    )
)
EepromDef = PpCvm441